<a href="https://colab.research.google.com/github/Ahmadzuko/Deep-Learning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

tensor_0d = tf.constant(4)
print(tensor_0d)

tf.Tensor(4, shape=(), dtype=int32)


In [7]:
tensor_1d = tf.constant([2, 0, -3])
print(tensor_1d)

tensor_1d = tf.constant([2, 0, -3.])
print(tensor_1d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)
tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)


In [8]:
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])
print(tensor_2d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [14]:
tensor_3d = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(tensor_3d)
print("shape = " + str(tensor_3d.shape))
print("dimension = " + str(tensor_3d.ndim))

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]], shape=(2, 3, 3), dtype=int32)
shape = (2, 3, 3)
dimension = 3


In [15]:
tensor_4d = tf.constant([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]], [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]])
print(tensor_4d)
print("shape = " + str(tensor_4d.shape))
print("dimension = " + str(tensor_4d.ndim))

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]


 [[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]], shape=(2, 2, 3, 3), dtype=int32)
shape = (2, 2, 3, 3)
dimension = 4
